#ifndef MARCO_DIALECT_SUNDIALS_IR_TYPES_H
#define MARCO_DIALECT_SUNDIALS_IR_TYPES_H

#include "mlir/IR/Types.h"

#define GET_TYPEDEF_CLASSES
#include "marco/Dialect/SUNDIALS/IR/SUNDIALSTypes.h.inc"

#endif // MARCO_DIALECT_SUNDIALS_IR_TYPES_H
