#ifndef MARCO_AST_BASEMODELICA_AST_H
#define MARCO_AST_BASEMODELICA_AST_H

// Just a convenience header file to include the AST nodes declarations

#include "CallStatement.h"
#include "ExternalFunctionCall.h"
#include "marco/AST/BaseModelica/Algorithm.h"
#include "marco/AST/BaseModelica/Annotation.h"
#include "marco/AST/BaseModelica/ArrayConstant.h"
#include "marco/AST/BaseModelica/ArrayDimension.h"
#include "marco/AST/BaseModelica/ArrayForGenerator.h"
#include "marco/AST/BaseModelica/ArrayGenerator.h"
#include "marco/AST/BaseModelica/AssignmentStatement.h"
#include "marco/AST/BaseModelica/BreakStatement.h"
#include "marco/AST/BaseModelica/Call.h"
#include "marco/AST/BaseModelica/Class.h"
#include "marco/AST/BaseModelica/ComponentReference.h"
#include "marco/AST/BaseModelica/ComponentReferenceEntry.h"
#include "marco/AST/BaseModelica/Constant.h"
#include "marco/AST/BaseModelica/EqualityEquation.h"
#include "marco/AST/BaseModelica/Equation.h"
#include "marco/AST/BaseModelica/EquationSection.h"
#include "marco/AST/BaseModelica/Expression.h"
#include "marco/AST/BaseModelica/ExpressionFunctionArgument.h"
#include "marco/AST/BaseModelica/ForEquation.h"
#include "marco/AST/BaseModelica/ForIndex.h"
#include "marco/AST/BaseModelica/ForStatement.h"
#include "marco/AST/BaseModelica/Function.h"
#include "marco/AST/BaseModelica/FunctionArgument.h"
#include "marco/AST/BaseModelica/IfEquation.h"
#include "marco/AST/BaseModelica/IfStatement.h"
#include "marco/AST/BaseModelica/Member.h"
#include "marco/AST/BaseModelica/Model.h"
#include "marco/AST/BaseModelica/Modification.h"
#include "marco/AST/BaseModelica/NamedFunctionArgument.h"
#include "marco/AST/BaseModelica/Operation.h"
#include "marco/AST/BaseModelica/Package.h"
#include "marco/AST/BaseModelica/Record.h"
#include "marco/AST/BaseModelica/ReductionFunctionArgument.h"
#include "marco/AST/BaseModelica/ReturnStatement.h"
#include "marco/AST/BaseModelica/Root.h"
#include "marco/AST/BaseModelica/Statement.h"
#include "marco/AST/BaseModelica/StatementsBlock.h"
#include "marco/AST/BaseModelica/Subscript.h"
#include "marco/AST/BaseModelica/Tuple.h"
#include "marco/AST/BaseModelica/Type.h"
#include "marco/AST/BaseModelica/TypePrefix.h"
#include "marco/AST/BaseModelica/WhenEquation.h"
#include "marco/AST/BaseModelica/WhenStatement.h"
#include "marco/AST/BaseModelica/WhileStatement.h"

#endif // MARCO_AST_BASEMODELICA_AST_H
