#ifndef MARCO_AST_BASEMODELICA_AST_H
#define MARCO_AST_BASEMODELICA_AST_H

// Just a convenience header file to include the AST nodes declarations

#include "marco/AST/BaseModelica/Node/Algorithm.h"
#include "marco/AST/BaseModelica/Node/Annotation.h"
#include "marco/AST/BaseModelica/Node/ArrayConstant.h"
#include "marco/AST/BaseModelica/Node/ArrayDimension.h"
#include "marco/AST/BaseModelica/Node/ArrayForGenerator.h"
#include "marco/AST/BaseModelica/Node/ArrayGenerator.h"
#include "marco/AST/BaseModelica/Node/AssignmentStatement.h"
#include "marco/AST/BaseModelica/Node/BreakStatement.h"
#include "marco/AST/BaseModelica/Node/Call.h"
#include "marco/AST/BaseModelica/Node/CallStatement.h"
#include "marco/AST/BaseModelica/Node/Class.h"
#include "marco/AST/BaseModelica/Node/ComponentReference.h"
#include "marco/AST/BaseModelica/Node/ComponentReferenceEntry.h"
#include "marco/AST/BaseModelica/Node/Constant.h"
#include "marco/AST/BaseModelica/Node/EqualityEquation.h"
#include "marco/AST/BaseModelica/Node/Equation.h"
#include "marco/AST/BaseModelica/Node/EquationSection.h"
#include "marco/AST/BaseModelica/Node/Expression.h"
#include "marco/AST/BaseModelica/Node/ExpressionFunctionArgument.h"
#include "marco/AST/BaseModelica/Node/ExternalFunctionCall.h"
#include "marco/AST/BaseModelica/Node/ForEquation.h"
#include "marco/AST/BaseModelica/Node/ForIndex.h"
#include "marco/AST/BaseModelica/Node/ForStatement.h"
#include "marco/AST/BaseModelica/Node/Function.h"
#include "marco/AST/BaseModelica/Node/FunctionArgument.h"
#include "marco/AST/BaseModelica/Node/IfEquation.h"
#include "marco/AST/BaseModelica/Node/IfStatement.h"
#include "marco/AST/BaseModelica/Node/Member.h"
#include "marco/AST/BaseModelica/Node/Model.h"
#include "marco/AST/BaseModelica/Node/Modification.h"
#include "marco/AST/BaseModelica/Node/NamedFunctionArgument.h"
#include "marco/AST/BaseModelica/Node/Operation.h"
#include "marco/AST/BaseModelica/Node/Package.h"
#include "marco/AST/BaseModelica/Node/Record.h"
#include "marco/AST/BaseModelica/Node/ReductionFunctionArgument.h"
#include "marco/AST/BaseModelica/Node/ReturnStatement.h"
#include "marco/AST/BaseModelica/Node/Root.h"
#include "marco/AST/BaseModelica/Node/Statement.h"
#include "marco/AST/BaseModelica/Node/StatementsBlock.h"
#include "marco/AST/BaseModelica/Node/Subscript.h"
#include "marco/AST/BaseModelica/Node/Tuple.h"
#include "marco/AST/BaseModelica/Node/Type.h"
#include "marco/AST/BaseModelica/Node/TypePrefix.h"
#include "marco/AST/BaseModelica/Node/WhenEquation.h"
#include "marco/AST/BaseModelica/Node/WhenStatement.h"
#include "marco/AST/BaseModelica/Node/WhileStatement.h"

#endif // MARCO_AST_BASEMODELICA_AST_H
