#ifndef MARCO_DIALECT_BASEMODELICA_TRANSFORMS_CONSTANTMATERIALIZABLETYPEINTERFACEIMPL_H
#define MARCO_DIALECT_BASEMODELICA_TRANSFORMS_CONSTANTMATERIALIZABLETYPEINTERFACEIMPL_H

namespace mlir
{
  class DialectRegistry;

  namespace bmodelica
  {
    void registerConstantMaterializableTypeInterfaceExternalModels(
        mlir::DialectRegistry& registry);
  }
}

#endif // MARCO_DIALECT_BASEMODELICA_TRANSFORMS_CONSTANTMATERIALIZABLETYPEINTERFACEIMPL_H
