#pragma once

// Just a convenience header file to include the AST nodes declarations

#include "ast/Algorithm.h"
#include "ast/Annotation.h"
#include "ast/Array.h"
#include "ast/Call.h"
#include "ast/Class.h"
#include "ast/ClassContainer.h"
#include "ast/ConditionalBlock.h"
#include "ast/Constant.h"
#include "ast/Equation.h"
#include "ast/Expression.h"
#include "ast/ForEquation.h"
#include "ast/Function.h"
#include "ast/Induction.h"
#include "ast/Member.h"
#include "ast/Modification.h"
#include "ast/Operation.h"
#include "ast/Package.h"
#include "ast/Record.h"
#include "ast/ReferenceAccess.h"
#include "ast/Statement.h"
#include "ast/Tuple.h"
#include "ast/Type.h"
#include "ast/TypePrefix.h"
