#ifndef MARCO_CODEGEN_CONVERSION_RUNTIMEMODELMETADATACONVERSION_RUNTIMEMODELMETADATACONVERSION_H
#define MARCO_CODEGEN_CONVERSION_RUNTIMEMODELMETADATACONVERSION_RUNTIMEMODELMETADATACONVERSION_H

#include "mlir/Pass/Pass.h"

namespace mlir
{
#define GEN_PASS_DECL_RUNTIMEMODELMETADATACONVERSIONPASS
#include "marco/Codegen/Conversion/Passes.h.inc"

  std::unique_ptr<mlir::Pass> createRuntimeModelMetadataConversionPass();
}

#endif // MARCO_CODEGEN_CONVERSION_RUNTIMEMODELMETADATACONVERSION_RUNTIMEMODELMETADATACONVERSION_H
