#ifndef MARCO_DIALECTS_SUNDIALS_TYPES_H
#define MARCO_DIALECTS_SUNDIALS_TYPES_H

#include "mlir/IR/Types.h"

#define GET_TYPEDEF_CLASSES
#include "marco/Dialect/SUNDIALS/SUNDIALSTypes.h.inc"

#endif // MARCO_DIALECTS_SUNDIALS_TYPES_H
