// RUN: modelica-opt %s --split-input-file --convert-bmodelica-to-arith | FileCheck %s

// CHECK-LABEL: @Integer
// CHECK: %[[range:.*]] = bmodelica.range.bounded %{{.*}}, %{{.*}}, %{{.*}}
// CHECK-DAG: %[[begin:.*]] = bmodelica.range.begin %[[range]]
// CHECK-DAG: %[[end:.*]] = bmodelica.range.end %[[range]]
// CHECK-DAG: %[[step:.*]] = bmodelica.range.step %[[range]]
// CHECK: %[[diff:.*]] = arith.subi %[[end]], %[[begin]]
// CHECK: %[[div:.*]] = arith.divsi %[[diff]], %[[step]]
// CHECK: %[[div_casted:.*]] = arith.index_cast %[[div]]
// CHECK: %[[one:.*]] = arith.constant 1
// CHECK: %[[add:.*]] = arith.addi %[[div_casted]], %[[one]]
// CHECK: return %[[add]]

func.func @Integer(%arg0: i64, %arg1: i64, %arg2: i64) -> index {
    %0 = bmodelica.range.bounded %arg0, %arg1, %arg2 : i64, i64, i64 -> !bmodelica<range i64>
    %1 = bmodelica.range.size %0 : !bmodelica<range i64>
    func.return %1 : index
}
