double acos(double);
double asin(double);
double atan(double);
double atan2(double, double);
double copysign(double, double);
double cos(double);
double cosh(double);
double exp(double);
double expm1(double);
double fabs(double);
double floor(double);
double log(double);
double log10(double);
double pow(double, double);
double scalbn(double, int);
double sin(double);
double sinh(double);
double sqrt(double);
double tan(double);
double tanh(double);
int __ieee754_rem_pio2(double, double *);
double __kernel_cos(double, double);
int __kernel_rem_pio2(double *, double *, int, int, int, const int *);
double __kernel_sin(double, double, int);
double __kernel_tan(double, double, int);
