double acos(double x);
double asin(double x);
double atan(double x);
double atan2(double y, double x);
double copysign(double x, double y);
double cos(double x);
double cosh(double x);
double exp(double x);
double expm1(double x);
double fabs(double x);
double floor(double x);
double log(double x);
double log10(double x);
double scalbn (double x, int n);
double sin(double x);
double sinh(double x);
double sqrt(double x);
double tan(double x);
double tanh(double x);
int __ieee754_rem_pio2(double x, double *y);
int __kernel_rem_pio2(double *x, double *y, int e0, int nx, int prec, const int *ipio2);
double __kernel_tan(double x, double y, int iy);
