#ifndef MARCO_TRANSFORMS_MODELSOLVING_EXTERNALSOLVERS_IDAOPTIONS_H
#define MARCO_TRANSFORMS_MODELSOLVING_EXTERNALSOLVERS_IDAOPTIONS_H

namespace marco::codegen
{
  struct IDAOptions
  {
    bool equidistantTimeGrid = false;
  };
}

#endif // MARCO_TRANSFORMS_MODELSOLVING_EXTERNALSOLVERS_IDAOPTIONS_H
