#ifndef MARCO_TRANSFORMS_MODELSOLVING_EXTERNALSOLVERS_KINSOLOPTIONS_H
#define MARCO_TRANSFORMS_MODELSOLVING_EXTERNALSOLVERS_KINSOLOPTIONS_H

namespace marco::codegen
{
  struct KINSOLOptions
  {
    bool equidistantTimeGrid = false;
  };
}

#endif // MARCO_TRANSFORMS_MODELSOLVING_EXTERNALSOLVERS_KINSOLOPTIONS_H
