#ifndef MARCO_AST_AST_H
#define MARCO_AST_AST_H

// Just a convenience header file to include the AST nodes declarations

#include "marco/AST/Node/Algorithm.h"
#include "marco/AST/Node/Annotation.h"
#include "marco/AST/Node/Array.h"
#include "marco/AST/Node/ArrayDimension.h"
#include "marco/AST/Node/AssignmentStatement.h"
#include "marco/AST/Node/BreakStatement.h"
#include "marco/AST/Node/Call.h"
#include "marco/AST/Node/Class.h"
#include "marco/AST/Node/Constant.h"
#include "marco/AST/Node/Equation.h"
#include "marco/AST/Node/EquationsBlock.h"
#include "marco/AST/Node/Expression.h"
#include "marco/AST/Node/ForEquation.h"
#include "marco/AST/Node/ForStatement.h"
#include "marco/AST/Node/Function.h"
#include "marco/AST/Node/IfStatement.h"
#include "marco/AST/Node/Induction.h"
#include "marco/AST/Node/Member.h"
#include "marco/AST/Node/Model.h"
#include "marco/AST/Node/Modification.h"
#include "marco/AST/Node/Operation.h"
#include "marco/AST/Node/Package.h"
#include "marco/AST/Node/Record.h"
#include "marco/AST/Node/ReferenceAccess.h"
#include "marco/AST/Node/ReturnStatement.h"
#include "marco/AST/Node/Root.h"
#include "marco/AST/Node/Statement.h"
#include "marco/AST/Node/StatementsBlock.h"
#include "marco/AST/Node/Tuple.h"
#include "marco/AST/Node/Type.h"
#include "marco/AST/Node/TypePrefix.h"
#include "marco/AST/Node/WhenStatement.h"
#include "marco/AST/Node/WhileStatement.h"

#endif // MARCO_AST_AST_H
